volumes:
  db_data:
  db_datamongo:
networks:
  mynetwork:
    driver: bridge

services:
  sqldata:
    networks:
      - mynetwork
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=YourStrong(!)Password 
    volumes:   
      - db_data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: always


  mongodb:
    image: mongo:8.0
    networks:
      - mynetwork
    environment:
      - MONGO_INITDB_ROOT_USERNAME=SAMongo
      - MONGO_INITDB_ROOT_PASSWORD=YourStrong(!)Password
    volumes:
      - db_datamongo:/data/db
    ports:
      - "27017:27017"

  nback_patient:
    networks:
      - mynetwork
    depends_on:
      - sqldata
    image: ${DOCKER_REGISTRY-}backpatient
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
   # ports: 
   #        - 8080:8080
    build:
      context: .
      dockerfile: back_Patient/Dockerfile

  detection_diabete:
    networks:
      - mynetwork
    depends_on:
      - nback_patient
      - nback_note
    image: ${DOCKER_REGISTRY-}detectiondiabete
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8095
      - ASPNETCORE_HTTPS_PORTS=8096
    ports: 
           - 8095:8095
    build:
      context: .
      dockerfile: ApiDetectionDiabete/Dockerfile

  nback_note:
    networks:
      - mynetwork
    depends_on:
      - mongodb
    image: ${DOCKER_REGISTRY-}backnote
   # ports:
   #        - 8090:8090
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090
      - ASPNETCORE_HTTPS_PORTS=8091
    build:
      context: .
      dockerfile: back_gestionDesNotes/Dockerfile

  nfront:
    networks:
      - mynetwork
    depends_on:
      - sqldata
    image: ${DOCKER_REGISTRY-}front
    build:
      context: .
      dockerfile: Front/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443

  apigateway:
    networks:
      - mynetwork
    image: ${DOCKER_REGISTRY-}apigateway
    depends_on:
      - nback_patient 
      - nback_note
      - detection_diabete
      - nfront
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5010
      - ASPNETCORE_HTTPS_PORTS=5011
    ports:
      - "5011:5011"

