volumes:
  db_data:

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=YourStrong(!)Password 
    volumes:
      - db_data:/var/opt/mssql  
    ports:
      - "1433:1433"
    restart: always

  back_patient:
    depends_on:
      - sqldata
    image: ${DOCKER_REGISTRY-}backpatient
    build:
      context: .
      dockerfile: back_Patient/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5010
      - ASPNETCORE_HTTPS_PORTS=5011
    ports:
      - "5011:5011"

  front:
    depends_on:
      - sqldata
    image: ${DOCKER_REGISTRY-}front
    build:
      context: .
      dockerfile: Front/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443

